### ISSUE TITLE
Inflector provides wrong result for `companies`

### ISSUE THREAD

**Issue by henrikbjorn** [kaspth/oaken#76]
`Oaken::Inflector.new.classify("companies")` should result in `Company` but actually results in `Companie` instead.

How would you like this fixed? Custom inflector code or using the inflector from active support?

**Comment by henrikbjorn** [comment]
Current workaround for others running into this

``` ruby
Oaken::Inflector.class_eval do
  def tableize(name) = name.tableize
  def classify(name) = name.classify
end
```

**Comment by kaspth** [comment]
@henrikbjorn hey, thanks for the issue! I ended up saving this for the RailsConf Hack Day. Originally I had intended doing something like `Oaken.inflector = ActiveSupport::Inflector`, but it doesn't really make sense.

So we just removed the inflector stuff and relied on `classify` and then the Active Record model's `table_name` instead.
